name: Auto-Update ZIP (Exclusion JAR)

on:
  push:
    paths:
      - '1.21.1/**' # Se déclenche si le contenu du dossier change

jobs:
  update-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Préparation et Compression
        run: |
          # 1. On crée une copie temporaire pour ne pas supprimer le fichier du dépôt
          mkdir dist_temp
          cp -r 1.21.1/* dist_temp/
          
          # 2. On supprime l'installeur neoforge spécifique de cette copie
          rm -f dist_temp/neoforge-21.1.227-installer.jar
          
          # 3. On compresse le contenu restant
          cd dist_temp
          zip -r ../dossier_1.21.1.zip .
          cd ..

      - name: Ajouter le ZIP à la Release 'zip'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: zip
          files: dossier_1.21.1.zip
          # 'append_body: true' ou 'false' ne change rien aux fichiers existants
          # L'action remplace seulement le fichier de même nom (le .zip)
