name: Build Mods ZIP from JSON

on:
  push:
    paths:
      - 'liste.json'         # Se déclenche si la liste est modifiée
      - '1.21.1/**'          # Ou si un fichier local est modifié

jobs:
  build-zip:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installation de jq
        run: sudo apt-get install jq -y

      - name: Téléchargement des Mods
        run: |
          # Création d'un dossier temporaire pour les mods
          mkdir -p temp_mods/mods
          
          # Extraction des URLs de la section "mods" uniquement
          # On boucle sur chaque URL trouvée dans le JSON
          urls=$(jq -r '.mods[].url' liste.json)
          
          for url in $urls; do
            echo "Téléchargement de : $url"
            # On télécharge dans le dossier temp_mods/mods
            curl -L "$url" --output-dir temp_mods/mods -O
          done

      - name: Création de l'archive ZIP
        run: |
          # On compresse le contenu du dossier temp_mods (qui contient le sous-dossier mods)
          cd temp_mods
          zip -r ../mods_1.21.1.zip .
          cd ..

      - name: Upload vers la Release 'zip'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: zip
          files: mods_1.21.1.zip
          fail_on_unmatched_files: true
